default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: r_indexer_development

test:
  <<: *default
  database: r_indexer_test

production:
  <<: *default
  database: r_indexer_production
  username: r_indexer
  password: <%= ENV['R_INDEXER_DATABASE_PASSWORD'] %>
